import { expect, test } from '@playwright/test'

test('karakter brifingi ve arşiv metinleri okunabilir, modeller doğru yönden başlar', async ({ page }) => {
  test.setTimeout(90_000)
  await page.setViewportSize({ width: 1500, height: 920 })
  await page.goto('/')
  await expect(page.locator('.loading-screen')).toHaveCount(0, { timeout: 60_000 })

  await expect(page.locator('.menu-battle-stage__categories')).toHaveCount(0)
  await expect(page.locator('.menu-fighter-name')).toHaveCount(2)
  const firstNames = await page.locator('.menu-fighter-name').allTextContents()
  await page.waitForTimeout(6_100)
  await expect.poll(async () => page.locator('.menu-fighter-name').allTextContents()).not.toEqual(firstNames)

  await page.getByRole('button', { name: 'KARAKTERLER' }).click()
  await expect(page.locator('.character-gallery')).toBeVisible()
  await expect(page.locator('.character-gallery__model canvas')).toBeVisible()
  await expect(page.locator('.difficulty-select--gallery button')).toHaveCount(4)
  const galleryFontSize = await page.locator('.difficulty-select--gallery button span').first().evaluate((node) => Number.parseFloat(getComputedStyle(node).fontSize))
  expect(galleryFontSize).toBeGreaterThanOrEqual(9)
  await expect(page.locator('.character-gallery__model > span')).toContainText('%100')
  await page.locator('.character-gallery__model').dispatchEvent('wheel', { deltaY: -200 })
  await expect(page.locator('.character-gallery__model > span')).toContainText('%124')
  for (let step = 0; step < 12; step += 1) {
    await page.locator('.character-gallery__model').dispatchEvent('wheel', { deltaY: -200 })
  }
  await expect(page.locator('.character-gallery__model > span')).toContainText('%280')
  const modelBounds = await page.locator('.character-gallery__model').boundingBox()
  expect(modelBounds).not.toBeNull()
  await page.mouse.move(modelBounds!.x + modelBounds!.width * 0.55, modelBounds!.y + modelBounds!.height * 0.55)
  await page.mouse.down({ button: 'right' })
  await page.mouse.move(modelBounds!.x + modelBounds!.width * 0.68, modelBounds!.y + modelBounds!.height * 0.7, { steps: 5 })
  await page.mouse.up({ button: 'right' })
  await expect(page.locator('.character-gallery__model')).not.toHaveAttribute('data-pan-x', '0.00')
  await expect(page.locator('.character-gallery__model')).not.toHaveAttribute('data-pan-y', '0.00')
  await page.waitForTimeout(700)
  await page.screenshot({ path: 'e2e-artifacts/character-gallery-readable-v7.png' })

  await page.getByRole('button', { name: 'Sonraki karakter' }).click()
  await page.waitForTimeout(700)
  await page.screenshot({ path: 'e2e-artifacts/samuray-jack-weapon-grip-v8.png' })

  await page.locator('.character-gallery > header button').click()
  await page.getByRole('button', { name: 'OYUNA BAŞLA' }).click()
  await expect(page.locator('.controls-screen')).toBeVisible()
  await expect(page.getByText(/4 sn boyunca en fazla 9 alev topu/i)).toBeVisible()
  const difficultyFontSize = await page.locator('.controls-screen .difficulty-select button span').first().evaluate((node) => Number.parseFloat(getComputedStyle(node).fontSize))
  expect(difficultyFontSize).toBeGreaterThanOrEqual(10)
  await page.waitForTimeout(700)
  await page.screenshot({ path: 'e2e-artifacts/hero-brief-facing-left-v7.png' })
})

test('savaş HUD yalnızca isim-can barını ve kalan canı gösterir', async ({ page }) => {
  test.setTimeout(90_000)
  await page.setViewportSize({ width: 1500, height: 920 })
  await page.goto('/')
  await expect(page.locator('.loading-screen')).toHaveCount(0, { timeout: 60_000 })
  await page.getByRole('button', { name: 'OYUNA BAŞLA' }).click()
  await page.getByRole('button', { name: 'SAVAŞA BAŞLA' }).click()
  await expect.poll(() => page.evaluate(() => window.__MERBUT__?.getSessionState().phase), { timeout: 10_000 }).toBe('playing')

  await expect(page.locator('.world-health--player')).toHaveCount(2)
  await expect(page.locator('.world-health--player small, .world-health--player em')).toHaveCount(0)
  await expect(page.locator('.player-hud__lives')).toHaveCount(2)
  await expect(page.locator('.player-hud footer', { hasText: 'SKOR' })).toHaveCount(0)

  const fireballLimit = await page.evaluate(() => {
    const session = window.__MERBUT__!.getSessionState()
    session.grantAbilityCharge('ali', 100)
    const start = performance.now()
    const attempts = Array.from({ length: 14 }, (_, index) => session.launchFireball(start + index * 280, 0, 0, 0))
    return { accepted: attempts.filter(Boolean).length, rejected: attempts.filter((accepted) => !accepted).length }
  })
  expect(fireballLimit).toEqual({ accepted: 9, rejected: 5 })
  await page.keyboard.press('s')
  await page.waitForTimeout(260)
  await page.screenshot({ path: 'e2e-artifacts/gameplay-weapons-live-hud-v7.png' })
})

test('çift zıplama çalışır ve kamera sürgüsü sahneyi canlı gösterir', async ({ page }) => {
  test.setTimeout(90_000)
  await page.setViewportSize({ width: 1500, height: 920 })
  await page.goto('/')
  await expect(page.locator('.loading-screen')).toHaveCount(0, { timeout: 60_000 })
  await page.getByRole('button', { name: 'OYUNA BAŞLA' }).click()
  await page.getByRole('button', { name: 'SAVAŞA BAŞLA' }).click()
  await expect.poll(() => page.evaluate(() => window.__MERBUT__?.getSessionState().phase), { timeout: 10_000 }).toBe('playing')

  await page.keyboard.press('w')
  await page.waitForTimeout(150)
  const firstJumpY = await page.evaluate(() => window.__MERBUT__!.getState().positions.ali[1])
  await page.keyboard.press('w')
  await page.waitForTimeout(150)
  const secondJumpY = await page.evaluate(() => window.__MERBUT__!.getState().positions.ali[1])
  expect(secondJumpY).toBeGreaterThan(firstJumpY + 0.35)

  await page.keyboard.press('Escape')
  await expect(page.locator('.pause-screen')).toBeVisible()
  await page.getByRole('button', { name: 'AYARLAR' }).click()
  const slider = page.getByRole('slider', { name: 'Kamera uzaklığı' })
  const bounds = await slider.boundingBox()
  expect(bounds).not.toBeNull()
  await page.mouse.move(bounds!.x + bounds!.width * 0.35, bounds!.y + bounds!.height / 2)
  await page.mouse.down()
  await page.mouse.move(bounds!.x + bounds!.width * 0.72, bounds!.y + bounds!.height / 2, { steps: 4 })
  await expect(page.locator('html')).toHaveClass(/is-camera-previewing/)
  await expect(page.locator('.pause-screen')).toHaveCSS('opacity', '0')
  await expect(page.locator('.audio-settings__panel')).toHaveCSS('visibility', 'hidden')
  await expect(page.locator('.camera-preview-readout')).toBeVisible()
  await page.screenshot({ path: 'e2e-artifacts/camera-live-preview-v8.png' })
  await page.mouse.up()
  await expect(page.locator('html')).not.toHaveClass(/is-camera-previewing/)
})
