export const PATCH_NOTES: readonly { version: string; title: string; notes: readonly string[] }[] = [
  {
    version: '3.1.1',
    title: 'Buton düzeltmeleri',
    notes: [
      'Bölüm Seç, Başarımlar, Yapımcılar ve Yama Notları ekranlarında GERİ butonu fareyle çalışmıyordu; bölüm seçimindeki parçalar da tıklanmıyordu. Düzeltildi.',
      'Prologdaki ATLA butonu ve tıklayarak sonraki panele geçme fareyle çalışmıyordu. Düzeltildi.',
      'Finaldeki yapımcılar kaydırmasının GEÇ butonu düzeltildi.',
      'Duraklatma menüsünden açılan Ayarlarda ok tuşları ve gamepad artık ayarların içinde geziniyor.',
      'Duraklatma → Kontroller ekranında Esc / gamepad B artık oyuna değil duraklatma menüsüne döner.',
    ],
  },
  {
    version: '3.1.0',
    title: 'Kayıt ve vitrin güncellemesi',
    notes: [
      'Ayarlar → Kayıt: ilerlemeyi (ayarların kalır) ya da her şeyi (fabrika ayarları) iki adımlı onayla sıfırla.',
      'Ana menüde kahraman menünün arkasından çıktı: sahnenin ortasında, düşmanla yüz yüze dövüşüyor.',
      'Vitrinde oyundaki hareketler: iki hızlı kesik ve dönerek kesen bitirici, ateş topu, kalkan.',
      'Menüde de gerçek kılıcı izleyen ışık izleri, kıvılcımlar ve kesik çizgileri; Jack katanasını kınından çekip geri sokuyor.',
      'Kılıç izleri artık ucu izleyen parlak bir hilal; ateş topu, kalkan ve karanlık küreler yeni ışık kabuklarıyla.',
      'Menü daha hafif: tam ekran gölge filtresi kaldırıldı. Grafik bildirimi yalnızca ilk açılışta çıkar.',
    ],
  },
  {
    version: '3.0.0',
    title: 'On Diyar güncellemesi',
    notes: [
      'Üç yeni diyar: Kum Saati Çölü, Böcek Dökümhanesi ve Şimşek Zirvesi; her biri kendi mekaniğiyle.',
      'Tüm tablolar yenilendi: her diyar, prolog ve final özgün “albüm kapağı” sanatıyla, iki katmanlı paralaksla çiziliyor.',
      'Üç vuruşluk saldırı zinciri ve dönerek kesen bitirici; Çifte Hamle; mermileri kılıçla savuşturma.',
      'Gerçek kılıcı izleyen ışık izleri, kıvılcım/mürekkep/kum parçacıkları, anime kesik çizgileri ve darbe kareleri.',
      'Jack katanasını kınında taşıyor; kılıçlar artık parlak çelik.',
      'Yeni düşmanlar: Serap, Böcek Dronları ve Ana Böcek. Yeni karakter: Yaşlı Keşiş.',
      'Prolog Aku’nun ağzından; Hz. Ali’nin “öfkeyle değil, hak için vururum” anı; Medine’ye uzanan final.',
      'Diyar girişleri albüm parçası kartı, bölüm seçimi plak parça listesi. 19 başarım.',
      'Boss olmayan diyarlara orta dalga eklendi; zorluk eki orta dalgalarda yarıya iner.',
      'Erişilebilirlik: renk körlüğü dostu saldırı uyarıları (sarı-beyaz, daha büyük halka).',
      'Bir düşmana yaslanınca arkandakine dönememe hatası düzeltildi.',
      'Bölüm seçimiyle bataklıktan başlarken Gölge’nin yanlışlıkla atlanması düzeltildi.',
      'itch.io’ya hazır: tüm varlık yolları göreli, tek komutla HTML5 paketi.',
    ],
  },
  {
    version: '2.0.0',
    title: 'Yedi Diyar güncellemesi',
    notes: [
      'Hikâye: prolog sinematiği, diyar başlık kartları, boss diyalogları ve “Hz. Ali’nin Zamanı” finali.',
      'Her diyara özgü mekanik: neon tabelalar, gelgit, bataklık suyu ve ateş böcekleri, lav çatlakları, ikiz çanlar, tipi ve buz, alev bacaları.',
      'Aku’ya üçüncü faz eklendi: Zaman Kırılması.',
      'Yeni düşman varyantları: Seçkin, Hayalet ve Kemik Devi.',
      'Vuruş hissi: hitstop, geri itme, sersemleme, saldırı uyarısı, kaçınma (dash) ve kusursuz kaçış ağır çekimi.',
      'Gamepad desteği, tuş atama, klavye düzenine göre tuş etiketleri ve erişilebilirlik ayarları.',
      'Özgün, uyarlanabilir müzik; diyar ortam sesleri ve yenilenen ses efektleri.',
      'Devam et, bölüm seçimi, rütbe sistemi, 14 başarım ve istatistikler.',
      'Her diyar için yeniden tasarlanan 3B set: yollar, ön plan siluetleri, temalı kapılar ve ortam aydınlatması.',
      'Siyah görünen zemin, kalabalık ve can barı renkleri düzeltildi.',
    ],
  },
  {
    version: '1.2.7',
    title: 'Biyom ilerleme düzeltmeleri',
    notes: ['Biyom geçişleri ve görseller sağlamlaştırıldı.'],
  },
]
